package com.example.administrator.fmxima.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.administrator.fmxima.entities.AlbumEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ALBUM_ENTITY".
*/
public class AlbumEntityDao extends AbstractDao<AlbumEntity, Long> {

    public static final String TABLENAME = "ALBUM_ENTITY";

    /**
     * Properties of entity AlbumEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property AlbumId = new Property(0, Long.class, "albumId", true, "ALBUM_ID");
        public final static Property CategoryId = new Property(1, Integer.class, "categoryId", false, "CATEGORY_ID");
        public final static Property CategoryName = new Property(2, String.class, "categoryName", false, "CATEGORY_NAME");
        public final static Property Title = new Property(3, String.class, "title", false, "TITLE");
        public final static Property CoverOrigin = new Property(4, String.class, "coverOrigin", false, "COVER_ORIGIN");
        public final static Property CoverSmall = new Property(5, String.class, "coverSmall", false, "COVER_SMALL");
        public final static Property CoverMiddle = new Property(6, String.class, "coverMiddle", false, "COVER_MIDDLE");
        public final static Property CoverLarge = new Property(7, String.class, "coverLarge", false, "COVER_LARGE");
        public final static Property CoverWebLarge = new Property(8, String.class, "coverWebLarge", false, "COVER_WEB_LARGE");
        public final static Property CreatedAt = new Property(9, java.util.Date.class, "createdAt", false, "CREATED_AT");
        public final static Property UpdatedAt = new Property(10, java.util.Date.class, "updatedAt", false, "UPDATED_AT");
        public final static Property Uid = new Property(11, Long.class, "uid", false, "UID");
        public final static Property Nickname = new Property(12, String.class, "nickname", false, "NICKNAME");
        public final static Property IsVerified = new Property(13, Boolean.class, "isVerified", false, "IS_VERIFIED");
        public final static Property AvatarPath = new Property(14, String.class, "avatarPath", false, "AVATAR_PATH");
        public final static Property ZoneId = new Property(15, String.class, "zoneId", false, "ZONE_ID");
        public final static Property Intro = new Property(16, String.class, "intro", false, "INTRO");
        public final static Property IntroRich = new Property(17, String.class, "introRich", false, "INTRO_RICH");
        public final static Property Tags = new Property(18, String.class, "tags", false, "TAGS");
        public final static Property Tracks = new Property(19, String.class, "tracks", false, "TRACKS");
        public final static Property Shares = new Property(20, String.class, "shares", false, "SHARES");
        public final static Property HasNew = new Property(21, Boolean.class, "hasNew", false, "HAS_NEW");
        public final static Property IsFavorite = new Property(22, Boolean.class, "isFavorite", false, "IS_FAVORITE");
        public final static Property PlayTimes = new Property(23, String.class, "playTimes", false, "PLAY_TIMES");
        public final static Property Status = new Property(24, String.class, "status", false, "STATUS");
        public final static Property SerializeStatus = new Property(25, String.class, "serializeStatus", false, "SERIALIZE_STATUS");
        public final static Property SerialState = new Property(26, String.class, "serialState", false, "SERIAL_STATE");
        public final static Property PlayTrackId = new Property(27, String.class, "playTrackId", false, "PLAY_TRACK_ID");
        public final static Property IsRecordDesc = new Property(28, Boolean.class, "isRecordDesc", false, "IS_RECORD_DESC");
    };


    public AlbumEntityDao(DaoConfig config) {
        super(config);
    }
    
    public AlbumEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ALBUM_ENTITY\" (" + //
                "\"ALBUM_ID\" INTEGER PRIMARY KEY ," + // 0: albumId
                "\"CATEGORY_ID\" INTEGER," + // 1: categoryId
                "\"CATEGORY_NAME\" TEXT," + // 2: categoryName
                "\"TITLE\" TEXT," + // 3: title
                "\"COVER_ORIGIN\" TEXT," + // 4: coverOrigin
                "\"COVER_SMALL\" TEXT," + // 5: coverSmall
                "\"COVER_MIDDLE\" TEXT," + // 6: coverMiddle
                "\"COVER_LARGE\" TEXT," + // 7: coverLarge
                "\"COVER_WEB_LARGE\" TEXT," + // 8: coverWebLarge
                "\"CREATED_AT\" INTEGER," + // 9: createdAt
                "\"UPDATED_AT\" INTEGER," + // 10: updatedAt
                "\"UID\" INTEGER," + // 11: uid
                "\"NICKNAME\" TEXT," + // 12: nickname
                "\"IS_VERIFIED\" INTEGER," + // 13: isVerified
                "\"AVATAR_PATH\" TEXT," + // 14: avatarPath
                "\"ZONE_ID\" TEXT," + // 15: zoneId
                "\"INTRO\" TEXT," + // 16: intro
                "\"INTRO_RICH\" TEXT," + // 17: introRich
                "\"TAGS\" TEXT," + // 18: tags
                "\"TRACKS\" TEXT," + // 19: tracks
                "\"SHARES\" TEXT," + // 20: shares
                "\"HAS_NEW\" INTEGER," + // 21: hasNew
                "\"IS_FAVORITE\" INTEGER," + // 22: isFavorite
                "\"PLAY_TIMES\" TEXT," + // 23: playTimes
                "\"STATUS\" TEXT," + // 24: status
                "\"SERIALIZE_STATUS\" TEXT," + // 25: serializeStatus
                "\"SERIAL_STATE\" TEXT," + // 26: serialState
                "\"PLAY_TRACK_ID\" TEXT," + // 27: playTrackId
                "\"IS_RECORD_DESC\" INTEGER);"); // 28: isRecordDesc
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ALBUM_ENTITY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, AlbumEntity entity) {
        stmt.clearBindings();
 
        Long albumId = entity.getAlbumId();
        if (albumId != null) {
            stmt.bindLong(1, albumId);
        }
 
        Integer categoryId = entity.getCategoryId();
        if (categoryId != null) {
            stmt.bindLong(2, categoryId);
        }
 
        String categoryName = entity.getCategoryName();
        if (categoryName != null) {
            stmt.bindString(3, categoryName);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(4, title);
        }
 
        String coverOrigin = entity.getCoverOrigin();
        if (coverOrigin != null) {
            stmt.bindString(5, coverOrigin);
        }
 
        String coverSmall = entity.getCoverSmall();
        if (coverSmall != null) {
            stmt.bindString(6, coverSmall);
        }
 
        String coverMiddle = entity.getCoverMiddle();
        if (coverMiddle != null) {
            stmt.bindString(7, coverMiddle);
        }
 
        String coverLarge = entity.getCoverLarge();
        if (coverLarge != null) {
            stmt.bindString(8, coverLarge);
        }
 
        String coverWebLarge = entity.getCoverWebLarge();
        if (coverWebLarge != null) {
            stmt.bindString(9, coverWebLarge);
        }
 
        java.util.Date createdAt = entity.getCreatedAt();
        if (createdAt != null) {
            stmt.bindLong(10, createdAt.getTime());
        }
 
        java.util.Date updatedAt = entity.getUpdatedAt();
        if (updatedAt != null) {
            stmt.bindLong(11, updatedAt.getTime());
        }
 
        Long uid = entity.getUid();
        if (uid != null) {
            stmt.bindLong(12, uid);
        }
 
        String nickname = entity.getNickname();
        if (nickname != null) {
            stmt.bindString(13, nickname);
        }
 
        Boolean isVerified = entity.getIsVerified();
        if (isVerified != null) {
            stmt.bindLong(14, isVerified ? 1L: 0L);
        }
 
        String avatarPath = entity.getAvatarPath();
        if (avatarPath != null) {
            stmt.bindString(15, avatarPath);
        }
 
        String zoneId = entity.getZoneId();
        if (zoneId != null) {
            stmt.bindString(16, zoneId);
        }
 
        String intro = entity.getIntro();
        if (intro != null) {
            stmt.bindString(17, intro);
        }
 
        String introRich = entity.getIntroRich();
        if (introRich != null) {
            stmt.bindString(18, introRich);
        }
 
        String tags = entity.getTags();
        if (tags != null) {
            stmt.bindString(19, tags);
        }
 
        String tracks = entity.getTracks();
        if (tracks != null) {
            stmt.bindString(20, tracks);
        }
 
        String shares = entity.getShares();
        if (shares != null) {
            stmt.bindString(21, shares);
        }
 
        Boolean hasNew = entity.getHasNew();
        if (hasNew != null) {
            stmt.bindLong(22, hasNew ? 1L: 0L);
        }
 
        Boolean isFavorite = entity.getIsFavorite();
        if (isFavorite != null) {
            stmt.bindLong(23, isFavorite ? 1L: 0L);
        }
 
        String playTimes = entity.getPlayTimes();
        if (playTimes != null) {
            stmt.bindString(24, playTimes);
        }
 
        String status = entity.getStatus();
        if (status != null) {
            stmt.bindString(25, status);
        }
 
        String serializeStatus = entity.getSerializeStatus();
        if (serializeStatus != null) {
            stmt.bindString(26, serializeStatus);
        }
 
        String serialState = entity.getSerialState();
        if (serialState != null) {
            stmt.bindString(27, serialState);
        }
 
        String playTrackId = entity.getPlayTrackId();
        if (playTrackId != null) {
            stmt.bindString(28, playTrackId);
        }
 
        Boolean isRecordDesc = entity.getIsRecordDesc();
        if (isRecordDesc != null) {
            stmt.bindLong(29, isRecordDesc ? 1L: 0L);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public AlbumEntity readEntity(Cursor cursor, int offset) {
        AlbumEntity entity = new AlbumEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // albumId
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // categoryId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // categoryName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // title
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // coverOrigin
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // coverSmall
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // coverMiddle
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // coverLarge
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // coverWebLarge
            cursor.isNull(offset + 9) ? null : new java.util.Date(cursor.getLong(offset + 9)), // createdAt
            cursor.isNull(offset + 10) ? null : new java.util.Date(cursor.getLong(offset + 10)), // updatedAt
            cursor.isNull(offset + 11) ? null : cursor.getLong(offset + 11), // uid
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // nickname
            cursor.isNull(offset + 13) ? null : cursor.getShort(offset + 13) != 0, // isVerified
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // avatarPath
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // zoneId
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // intro
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // introRich
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // tags
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // tracks
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // shares
            cursor.isNull(offset + 21) ? null : cursor.getShort(offset + 21) != 0, // hasNew
            cursor.isNull(offset + 22) ? null : cursor.getShort(offset + 22) != 0, // isFavorite
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // playTimes
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // status
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // serializeStatus
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // serialState
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // playTrackId
            cursor.isNull(offset + 28) ? null : cursor.getShort(offset + 28) != 0 // isRecordDesc
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, AlbumEntity entity, int offset) {
        entity.setAlbumId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCategoryId(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setCategoryName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTitle(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCoverOrigin(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCoverSmall(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setCoverMiddle(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setCoverLarge(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setCoverWebLarge(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setCreatedAt(cursor.isNull(offset + 9) ? null : new java.util.Date(cursor.getLong(offset + 9)));
        entity.setUpdatedAt(cursor.isNull(offset + 10) ? null : new java.util.Date(cursor.getLong(offset + 10)));
        entity.setUid(cursor.isNull(offset + 11) ? null : cursor.getLong(offset + 11));
        entity.setNickname(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setIsVerified(cursor.isNull(offset + 13) ? null : cursor.getShort(offset + 13) != 0);
        entity.setAvatarPath(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setZoneId(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setIntro(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setIntroRich(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setTags(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setTracks(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setShares(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setHasNew(cursor.isNull(offset + 21) ? null : cursor.getShort(offset + 21) != 0);
        entity.setIsFavorite(cursor.isNull(offset + 22) ? null : cursor.getShort(offset + 22) != 0);
        entity.setPlayTimes(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setStatus(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setSerializeStatus(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setSerialState(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setPlayTrackId(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setIsRecordDesc(cursor.isNull(offset + 28) ? null : cursor.getShort(offset + 28) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(AlbumEntity entity, long rowId) {
        entity.setAlbumId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(AlbumEntity entity) {
        if(entity != null) {
            return entity.getAlbumId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
