package com.example.administrator.fmxima.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.example.administrator.fmxima.dao.DiscoverEntityDao;
import com.example.administrator.fmxima.dao.RecommendsEntityDao;
import com.example.administrator.fmxima.dao.AlbumEntityDao;
import com.example.administrator.fmxima.dao.TrackEntityDao;
import com.example.administrator.fmxima.dao.FocusImageEntityDao;
import com.example.administrator.fmxima.dao.SpecialColumnEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        DiscoverEntityDao.createTable(db, ifNotExists);
        RecommendsEntityDao.createTable(db, ifNotExists);
        AlbumEntityDao.createTable(db, ifNotExists);
        TrackEntityDao.createTable(db, ifNotExists);
        FocusImageEntityDao.createTable(db, ifNotExists);
        SpecialColumnEntityDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        DiscoverEntityDao.dropTable(db, ifExists);
        RecommendsEntityDao.dropTable(db, ifExists);
        AlbumEntityDao.dropTable(db, ifExists);
        TrackEntityDao.dropTable(db, ifExists);
        FocusImageEntityDao.dropTable(db, ifExists);
        SpecialColumnEntityDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(DiscoverEntityDao.class);
        registerDaoClass(RecommendsEntityDao.class);
        registerDaoClass(AlbumEntityDao.class);
        registerDaoClass(TrackEntityDao.class);
        registerDaoClass(FocusImageEntityDao.class);
        registerDaoClass(SpecialColumnEntityDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
