package com.example.administrator.fmxima.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.administrator.fmxima.entities.DiscoverEntity;
import com.example.administrator.fmxima.entities.RecommendsEntity;
import com.example.administrator.fmxima.entities.AlbumEntity;
import com.example.administrator.fmxima.entities.TrackEntity;
import com.example.administrator.fmxima.entities.FocusImageEntity;
import com.example.administrator.fmxima.entities.SpecialColumnEntity;

import com.example.administrator.fmxima.dao.DiscoverEntityDao;
import com.example.administrator.fmxima.dao.RecommendsEntityDao;
import com.example.administrator.fmxima.dao.AlbumEntityDao;
import com.example.administrator.fmxima.dao.TrackEntityDao;
import com.example.administrator.fmxima.dao.FocusImageEntityDao;
import com.example.administrator.fmxima.dao.SpecialColumnEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig discoverEntityDaoConfig;
    private final DaoConfig recommendsEntityDaoConfig;
    private final DaoConfig albumEntityDaoConfig;
    private final DaoConfig trackEntityDaoConfig;
    private final DaoConfig focusImageEntityDaoConfig;
    private final DaoConfig specialColumnEntityDaoConfig;

    private final DiscoverEntityDao discoverEntityDao;
    private final RecommendsEntityDao recommendsEntityDao;
    private final AlbumEntityDao albumEntityDao;
    private final TrackEntityDao trackEntityDao;
    private final FocusImageEntityDao focusImageEntityDao;
    private final SpecialColumnEntityDao specialColumnEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        discoverEntityDaoConfig = daoConfigMap.get(DiscoverEntityDao.class).clone();
        discoverEntityDaoConfig.initIdentityScope(type);

        recommendsEntityDaoConfig = daoConfigMap.get(RecommendsEntityDao.class).clone();
        recommendsEntityDaoConfig.initIdentityScope(type);

        albumEntityDaoConfig = daoConfigMap.get(AlbumEntityDao.class).clone();
        albumEntityDaoConfig.initIdentityScope(type);

        trackEntityDaoConfig = daoConfigMap.get(TrackEntityDao.class).clone();
        trackEntityDaoConfig.initIdentityScope(type);

        focusImageEntityDaoConfig = daoConfigMap.get(FocusImageEntityDao.class).clone();
        focusImageEntityDaoConfig.initIdentityScope(type);

        specialColumnEntityDaoConfig = daoConfigMap.get(SpecialColumnEntityDao.class).clone();
        specialColumnEntityDaoConfig.initIdentityScope(type);

        discoverEntityDao = new DiscoverEntityDao(discoverEntityDaoConfig, this);
        recommendsEntityDao = new RecommendsEntityDao(recommendsEntityDaoConfig, this);
        albumEntityDao = new AlbumEntityDao(albumEntityDaoConfig, this);
        trackEntityDao = new TrackEntityDao(trackEntityDaoConfig, this);
        focusImageEntityDao = new FocusImageEntityDao(focusImageEntityDaoConfig, this);
        specialColumnEntityDao = new SpecialColumnEntityDao(specialColumnEntityDaoConfig, this);

        registerDao(DiscoverEntity.class, discoverEntityDao);
        registerDao(RecommendsEntity.class, recommendsEntityDao);
        registerDao(AlbumEntity.class, albumEntityDao);
        registerDao(TrackEntity.class, trackEntityDao);
        registerDao(FocusImageEntity.class, focusImageEntityDao);
        registerDao(SpecialColumnEntity.class, specialColumnEntityDao);
    }
    
    public void clear() {
        discoverEntityDaoConfig.getIdentityScope().clear();
        recommendsEntityDaoConfig.getIdentityScope().clear();
        albumEntityDaoConfig.getIdentityScope().clear();
        trackEntityDaoConfig.getIdentityScope().clear();
        focusImageEntityDaoConfig.getIdentityScope().clear();
        specialColumnEntityDaoConfig.getIdentityScope().clear();
    }

    public DiscoverEntityDao getDiscoverEntityDao() {
        return discoverEntityDao;
    }

    public RecommendsEntityDao getRecommendsEntityDao() {
        return recommendsEntityDao;
    }

    public AlbumEntityDao getAlbumEntityDao() {
        return albumEntityDao;
    }

    public TrackEntityDao getTrackEntityDao() {
        return trackEntityDao;
    }

    public FocusImageEntityDao getFocusImageEntityDao() {
        return focusImageEntityDao;
    }

    public SpecialColumnEntityDao getSpecialColumnEntityDao() {
        return specialColumnEntityDao;
    }

}
