package com.example.administrator.fmxima.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.administrator.fmxima.entities.HotRecommendsEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HOT_RECOMMENDS_ENTITY".
*/
public class HotRecommendsEntityDao extends AbstractDao<HotRecommendsEntity, Void> {

    public static final String TABLENAME = "HOT_RECOMMENDS_ENTITY";

    /**
     * Properties of entity HotRecommendsEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Title = new Property(0, String.class, "title", false, "TITLE");
        public final static Property ContentType = new Property(1, String.class, "contentType", false, "CONTENT_TYPE");
        public final static Property IsFinished = new Property(2, Boolean.class, "isFinished", false, "IS_FINISHED");
        public final static Property Count = new Property(3, Integer.class, "count", false, "COUNT");
        public final static Property HasMore = new Property(4, String.class, "hasMore", false, "HAS_MORE");
    };


    public HotRecommendsEntityDao(DaoConfig config) {
        super(config);
    }
    
    public HotRecommendsEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HOT_RECOMMENDS_ENTITY\" (" + //
                "\"TITLE\" TEXT," + // 0: title
                "\"CONTENT_TYPE\" TEXT," + // 1: contentType
                "\"IS_FINISHED\" INTEGER," + // 2: isFinished
                "\"COUNT\" INTEGER," + // 3: count
                "\"HAS_MORE\" TEXT);"); // 4: hasMore
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HOT_RECOMMENDS_ENTITY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, HotRecommendsEntity entity) {
        stmt.clearBindings();
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(1, title);
        }
 
        String contentType = entity.getContentType();
        if (contentType != null) {
            stmt.bindString(2, contentType);
        }
 
        Boolean isFinished = entity.getIsFinished();
        if (isFinished != null) {
            stmt.bindLong(3, isFinished ? 1L: 0L);
        }
 
        Integer count = entity.getCount();
        if (count != null) {
            stmt.bindLong(4, count);
        }
 
        String hasMore = entity.getHasMore();
        if (hasMore != null) {
            stmt.bindString(5, hasMore);
        }
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public HotRecommendsEntity readEntity(Cursor cursor, int offset) {
        HotRecommendsEntity entity = new HotRecommendsEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // title
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // contentType
            cursor.isNull(offset + 2) ? null : cursor.getShort(offset + 2) != 0, // isFinished
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // count
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // hasMore
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, HotRecommendsEntity entity, int offset) {
        entity.setTitle(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setContentType(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setIsFinished(cursor.isNull(offset + 2) ? null : cursor.getShort(offset + 2) != 0);
        entity.setCount(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setHasMore(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(HotRecommendsEntity entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(HotRecommendsEntity entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
