package com.example.administrator.fmxima.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ALBUM_ENTITY".
 */
public class AlbumEntity {

    private Long albumId;
    private Integer categoryId;
    private String categoryName;
    private String title;
    private String coverOrigin;
    private String coverSmall;
    private String coverMiddle;
    private String coverLarge;
    private String coverWebLarge;
    private java.util.Date createdAt;
    private java.util.Date updatedAt;
    private Long uid;
    private String nickname;
    private Boolean isVerified;
    private String avatarPath;
    private String zoneId;
    private String intro;
    private String introRich;
    private String tags;
    private String tracks;
    private String shares;
    private Boolean hasNew;
    private Boolean isFavorite;
    private String playTimes;
    private String status;
    private String serializeStatus;
    private String serialState;
    private String playTrackId;
    private Boolean isRecordDesc;
    private String trackTitle;

    public Boolean getVerified() {
        return isVerified;
    }

    public void setVerified(Boolean verified) {
        isVerified = verified;
    }

    public Boolean getFavorite() {
        return isFavorite;
    }

    public void setFavorite(Boolean favorite) {
        isFavorite = favorite;
    }

    public Boolean getRecordDesc() {
        return isRecordDesc;
    }

    public void setRecordDesc(Boolean recordDesc) {
        isRecordDesc = recordDesc;
    }

    public String getTrackTitle() {
        return trackTitle;
    }

    public void setTrackTitle(String trackTitle) {
        this.trackTitle = trackTitle;
    }

    public AlbumEntity() {
    }

    public AlbumEntity(Long albumId) {
        this.albumId = albumId;
    }

    public AlbumEntity(Long albumId, Integer categoryId, String categoryName, String title, String coverOrigin, String coverSmall, String coverMiddle, String coverLarge, String coverWebLarge, java.util.Date createdAt, java.util.Date updatedAt, Long uid, String nickname, Boolean isVerified, String avatarPath, String zoneId, String intro, String introRich, String tags, String tracks, String shares, Boolean hasNew, Boolean isFavorite, String playTimes, String status, String serializeStatus, String serialState, String playTrackId, Boolean isRecordDesc) {
        this.albumId = albumId;
        this.categoryId = categoryId;
        this.categoryName = categoryName;
        this.title = title;
        this.coverOrigin = coverOrigin;
        this.coverSmall = coverSmall;
        this.coverMiddle = coverMiddle;
        this.coverLarge = coverLarge;
        this.coverWebLarge = coverWebLarge;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.uid = uid;
        this.nickname = nickname;
        this.isVerified = isVerified;
        this.avatarPath = avatarPath;
        this.zoneId = zoneId;
        this.intro = intro;
        this.introRich = introRich;
        this.tags = tags;
        this.tracks = tracks;
        this.shares = shares;
        this.hasNew = hasNew;
        this.isFavorite = isFavorite;
        this.playTimes = playTimes;
        this.status = status;
        this.serializeStatus = serializeStatus;
        this.serialState = serialState;
        this.playTrackId = playTrackId;
        this.isRecordDesc = isRecordDesc;
    }

    public Long getAlbumId() {
        return albumId;
    }

    public void setAlbumId(Long albumId) {
        this.albumId = albumId;
    }

    public Integer getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    public String getCategoryName() {
        return categoryName;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getCoverOrigin() {
        return coverOrigin;
    }

    public void setCoverOrigin(String coverOrigin) {
        this.coverOrigin = coverOrigin;
    }

    public String getCoverSmall() {
        return coverSmall;
    }

    public void setCoverSmall(String coverSmall) {
        this.coverSmall = coverSmall;
    }

    public String getCoverMiddle() {
        return coverMiddle;
    }

    public void setCoverMiddle(String coverMiddle) {
        this.coverMiddle = coverMiddle;
    }

    public String getCoverLarge() {
        return coverLarge;
    }

    public void setCoverLarge(String coverLarge) {
        this.coverLarge = coverLarge;
    }

    public String getCoverWebLarge() {
        return coverWebLarge;
    }

    public void setCoverWebLarge(String coverWebLarge) {
        this.coverWebLarge = coverWebLarge;
    }

    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Long getUid() {
        return uid;
    }

    public void setUid(Long uid) {
        this.uid = uid;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public Boolean getIsVerified() {
        return isVerified;
    }

    public void setIsVerified(Boolean isVerified) {
        this.isVerified = isVerified;
    }

    public String getAvatarPath() {
        return avatarPath;
    }

    public void setAvatarPath(String avatarPath) {
        this.avatarPath = avatarPath;
    }

    public String getZoneId() {
        return zoneId;
    }

    public void setZoneId(String zoneId) {
        this.zoneId = zoneId;
    }

    public String getIntro() {
        return intro;
    }

    public void setIntro(String intro) {
        this.intro = intro;
    }

    public String getIntroRich() {
        return introRich;
    }

    public void setIntroRich(String introRich) {
        this.introRich = introRich;
    }

    public String getTags() {
        return tags;
    }

    public void setTags(String tags) {
        this.tags = tags;
    }

    public String getTracks() {
        return tracks;
    }

    public void setTracks(String tracks) {
        this.tracks = tracks;
    }

    public String getShares() {
        return shares;
    }

    public void setShares(String shares) {
        this.shares = shares;
    }

    public Boolean getHasNew() {
        return hasNew;
    }

    public void setHasNew(Boolean hasNew) {
        this.hasNew = hasNew;
    }

    public Boolean getIsFavorite() {
        return isFavorite;
    }

    public void setIsFavorite(Boolean isFavorite) {
        this.isFavorite = isFavorite;
    }

    public String getPlayTimes() {
        return playTimes;
    }

    public void setPlayTimes(String playTimes) {
        this.playTimes = playTimes;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getSerializeStatus() {
        return serializeStatus;
    }

    public void setSerializeStatus(String serializeStatus) {
        this.serializeStatus = serializeStatus;
    }

    public String getSerialState() {
        return serialState;
    }

    public void setSerialState(String serialState) {
        this.serialState = serialState;
    }

    public String getPlayTrackId() {
        return playTrackId;
    }

    public void setPlayTrackId(String playTrackId) {
        this.playTrackId = playTrackId;
    }

    public Boolean getIsRecordDesc() {
        return isRecordDesc;
    }

    public void setIsRecordDesc(Boolean isRecordDesc) {
        this.isRecordDesc = isRecordDesc;
    }

}
