package com.example.administrator.fmxima.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BULLET_AREA_ENTITY".
 */
public class BulletAreaEntity {

    private Long trackId;
    private String title;
    private String coverMiddle;
    private String tags;
    private String playPath32;
    private String playPath64;
    private String albumId;
    private String albumTitle;
    private String favoritesCounts;
    private String playsCounts;
    private String commentsCounts;
    private String sharesCounts;

    public BulletAreaEntity() {
    }

    public BulletAreaEntity(Long trackId) {
        this.trackId = trackId;
    }

    public BulletAreaEntity(Long trackId, String title, String coverMiddle, String tags, String playPath32, String playPath64, String albumId, String albumTitle, String favoritesCounts, String playsCounts, String commentsCounts, String sharesCounts) {
        this.trackId = trackId;
        this.title = title;
        this.coverMiddle = coverMiddle;
        this.tags = tags;
        this.playPath32 = playPath32;
        this.playPath64 = playPath64;
        this.albumId = albumId;
        this.albumTitle = albumTitle;
        this.favoritesCounts = favoritesCounts;
        this.playsCounts = playsCounts;
        this.commentsCounts = commentsCounts;
        this.sharesCounts = sharesCounts;
    }

    public Long getTrackId() {
        return trackId;
    }

    public void setTrackId(Long trackId) {
        this.trackId = trackId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getCoverMiddle() {
        return coverMiddle;
    }

    public void setCoverMiddle(String coverMiddle) {
        this.coverMiddle = coverMiddle;
    }

    public String getTags() {
        return tags;
    }

    public void setTags(String tags) {
        this.tags = tags;
    }

    public String getPlayPath32() {
        return playPath32;
    }

    public void setPlayPath32(String playPath32) {
        this.playPath32 = playPath32;
    }

    public String getPlayPath64() {
        return playPath64;
    }

    public void setPlayPath64(String playPath64) {
        this.playPath64 = playPath64;
    }

    public String getAlbumId() {
        return albumId;
    }

    public void setAlbumId(String albumId) {
        this.albumId = albumId;
    }

    public String getAlbumTitle() {
        return albumTitle;
    }

    public void setAlbumTitle(String albumTitle) {
        this.albumTitle = albumTitle;
    }

    public String getFavoritesCounts() {
        return favoritesCounts;
    }

    public void setFavoritesCounts(String favoritesCounts) {
        this.favoritesCounts = favoritesCounts;
    }

    public String getPlaysCounts() {
        return playsCounts;
    }

    public void setPlaysCounts(String playsCounts) {
        this.playsCounts = playsCounts;
    }

    public String getCommentsCounts() {
        return commentsCounts;
    }

    public void setCommentsCounts(String commentsCounts) {
        this.commentsCounts = commentsCounts;
    }

    public String getSharesCounts() {
        return sharesCounts;
    }

    public void setSharesCounts(String sharesCounts) {
        this.sharesCounts = sharesCounts;
    }

}
