package com.example.administrator.fmxima.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "HOT_RECOMMENDS_ENTITY".
 */
public class HotRecommendsEntity {

    private String title;
    private String contentType;
    private Boolean isFinished;
    private Integer count;
    private String hasMore;

    public HotRecommendsEntity() {
    }

    public HotRecommendsEntity(String title, String contentType, Boolean isFinished, Integer count, String hasMore) {
        this.title = title;
        this.contentType = contentType;
        this.isFinished = isFinished;
        this.count = count;
        this.hasMore = hasMore;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContentType() {
        return contentType;
    }

    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    public Boolean getIsFinished() {
        return isFinished;
    }

    public void setIsFinished(Boolean isFinished) {
        this.isFinished = isFinished;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public String getHasMore() {
        return hasMore;
    }

    public void setHasMore(String hasMore) {
        this.hasMore = hasMore;
    }

}
