package com.example.administrator.fmxima.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.util.ArrayList;

/**
 * Entity mapped to table "RECOMMENDS_ENTITY".
 */
public class RecommendsEntity {

    private String title;
    private String contentType;
    private Boolean isFinished;
    private String categoryId;
    private Integer count;
    private Boolean hasMore;

    private ArrayList<AlbumEntity> list;

    public Boolean getFinished() {
        return isFinished;
    }

    public void setFinished(Boolean finished) {
        isFinished = finished;
    }

    public ArrayList<AlbumEntity> getList() {
        return list;
    }

    public void setList(ArrayList<AlbumEntity> list) {
        this.list = list;
    }

    public RecommendsEntity() {
    }

    public RecommendsEntity(String title, String contentType, Boolean isFinished, String categoryId, Integer count, Boolean hasMore) {
        this.title = title;
        this.contentType = contentType;
        this.isFinished = isFinished;
        this.categoryId = categoryId;
        this.count = count;
        this.hasMore = hasMore;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContentType() {
        return contentType;
    }

    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    public Boolean getIsFinished() {
        return isFinished;
    }

    public void setIsFinished(Boolean isFinished) {
        this.isFinished = isFinished;
    }

    public String getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public Boolean getHasMore() {
        return hasMore;
    }

    public void setHasMore(Boolean hasMore) {
        this.hasMore = hasMore;
    }

}
