package com.example.administrator.fmxima.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SPECIAL_COLUMN_ENTITY".
 */
public class SpecialColumnEntity {

    private String columnType;
    private String specialId;
    private String title;
    private String subtitle;
    private String footnote;
    private String coverPath;
    private String contentType;

    public SpecialColumnEntity() {
    }

    public SpecialColumnEntity(String columnType, String specialId, String title, String subtitle, String footnote, String coverPath, String contentType) {
        this.columnType = columnType;
        this.specialId = specialId;
        this.title = title;
        this.subtitle = subtitle;
        this.footnote = footnote;
        this.coverPath = coverPath;
        this.contentType = contentType;
    }

    public String getColumnType() {
        return columnType;
    }

    public void setColumnType(String columnType) {
        this.columnType = columnType;
    }

    public String getSpecialId() {
        return specialId;
    }

    public void setSpecialId(String specialId) {
        this.specialId = specialId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getSubtitle() {
        return subtitle;
    }

    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }

    public String getFootnote() {
        return footnote;
    }

    public void setFootnote(String footnote) {
        this.footnote = footnote;
    }

    public String getCoverPath() {
        return coverPath;
    }

    public void setCoverPath(String coverPath) {
        this.coverPath = coverPath;
    }

    public String getContentType() {
        return contentType;
    }

    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

}
