package com.example.administrator.fmxima.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TRACK_ENTITY".
 */
public class TrackEntity {

    private Long trackId;
    private Long uid;
    private String playUrl64;
    private String playUrl32;
    private String downloadUrl;
    private String playPathAacv164;
    private String playPathAacv224;
    private String downloadAacUrl;
    private String title;
    private String duration;
    private String albumId;
    private String albumTitle;
    private String albumImage;
    private String processState;
    private String createdAt;
    private String coverSmall;
    private String coverMiddle;
    private String coverLarge;
    private String nickname;
    private String smallLogo;
    private String userSource;
    private String orderNum;
    private String opType;
    private Boolean isPublic;
    private String likes;
    private String playtimes;
    private String comments;
    private String shares;
    private String status;
    private String downloadSize;
    private String downloadAacSize;
    private String commentsCounts;

    public Boolean getPublic() {
        return isPublic;
    }

    public void setPublic(Boolean aPublic) {
        isPublic = aPublic;
    }

    public String getCommentsCounts() {
        return commentsCounts;
    }

    public void setCommentsCounts(String commentsCounts) {
        this.commentsCounts = commentsCounts;
    }

    public TrackEntity() {
    }

    public TrackEntity(Long trackId) {
        this.trackId = trackId;
    }

    public TrackEntity(Long trackId, Long uid, String playUrl64, String playUrl32, String downloadUrl, String playPathAacv164, String playPathAacv224, String downloadAacUrl, String title, String duration, String albumId, String albumTitle, String albumImage, String processState, String createdAt, String coverSmall, String coverMiddle, String coverLarge, String nickname, String smallLogo, String userSource, String orderNum, String opType, Boolean isPublic, String likes, String playtimes, String comments, String shares, String status, String downloadSize, String downloadAacSize) {
        this.trackId = trackId;
        this.uid = uid;
        this.playUrl64 = playUrl64;
        this.playUrl32 = playUrl32;
        this.downloadUrl = downloadUrl;
        this.playPathAacv164 = playPathAacv164;
        this.playPathAacv224 = playPathAacv224;
        this.downloadAacUrl = downloadAacUrl;
        this.title = title;
        this.duration = duration;
        this.albumId = albumId;
        this.albumTitle = albumTitle;
        this.albumImage = albumImage;
        this.processState = processState;
        this.createdAt = createdAt;
        this.coverSmall = coverSmall;
        this.coverMiddle = coverMiddle;
        this.coverLarge = coverLarge;
        this.nickname = nickname;
        this.smallLogo = smallLogo;
        this.userSource = userSource;
        this.orderNum = orderNum;
        this.opType = opType;
        this.isPublic = isPublic;
        this.likes = likes;
        this.playtimes = playtimes;
        this.comments = comments;
        this.shares = shares;
        this.status = status;
        this.downloadSize = downloadSize;
        this.downloadAacSize = downloadAacSize;
    }

    public Long getTrackId() {
        return trackId;
    }

    public void setTrackId(Long trackId) {
        this.trackId = trackId;
    }

    public Long getUid() {
        return uid;
    }

    public void setUid(Long uid) {
        this.uid = uid;
    }

    public String getPlayUrl64() {
        return playUrl64;
    }

    public void setPlayUrl64(String playUrl64) {
        this.playUrl64 = playUrl64;
    }

    public String getPlayUrl32() {
        return playUrl32;
    }

    public void setPlayUrl32(String playUrl32) {
        this.playUrl32 = playUrl32;
    }

    public String getDownloadUrl() {
        return downloadUrl;
    }

    public void setDownloadUrl(String downloadUrl) {
        this.downloadUrl = downloadUrl;
    }

    public String getPlayPathAacv164() {
        return playPathAacv164;
    }

    public void setPlayPathAacv164(String playPathAacv164) {
        this.playPathAacv164 = playPathAacv164;
    }

    public String getPlayPathAacv224() {
        return playPathAacv224;
    }

    public void setPlayPathAacv224(String playPathAacv224) {
        this.playPathAacv224 = playPathAacv224;
    }

    public String getDownloadAacUrl() {
        return downloadAacUrl;
    }

    public void setDownloadAacUrl(String downloadAacUrl) {
        this.downloadAacUrl = downloadAacUrl;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDuration() {
        return duration;
    }

    public void setDuration(String duration) {
        this.duration = duration;
    }

    public String getAlbumId() {
        return albumId;
    }

    public void setAlbumId(String albumId) {
        this.albumId = albumId;
    }

    public String getAlbumTitle() {
        return albumTitle;
    }

    public void setAlbumTitle(String albumTitle) {
        this.albumTitle = albumTitle;
    }

    public String getAlbumImage() {
        return albumImage;
    }

    public void setAlbumImage(String albumImage) {
        this.albumImage = albumImage;
    }

    public String getProcessState() {
        return processState;
    }

    public void setProcessState(String processState) {
        this.processState = processState;
    }

    public String getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    public String getCoverSmall() {
        return coverSmall;
    }

    public void setCoverSmall(String coverSmall) {
        this.coverSmall = coverSmall;
    }

    public String getCoverMiddle() {
        return coverMiddle;
    }

    public void setCoverMiddle(String coverMiddle) {
        this.coverMiddle = coverMiddle;
    }

    public String getCoverLarge() {
        return coverLarge;
    }

    public void setCoverLarge(String coverLarge) {
        this.coverLarge = coverLarge;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getSmallLogo() {
        return smallLogo;
    }

    public void setSmallLogo(String smallLogo) {
        this.smallLogo = smallLogo;
    }

    public String getUserSource() {
        return userSource;
    }

    public void setUserSource(String userSource) {
        this.userSource = userSource;
    }

    public String getOrderNum() {
        return orderNum;
    }

    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum;
    }

    public String getOpType() {
        return opType;
    }

    public void setOpType(String opType) {
        this.opType = opType;
    }

    public Boolean getIsPublic() {
        return isPublic;
    }

    public void setIsPublic(Boolean isPublic) {
        this.isPublic = isPublic;
    }

    public String getLikes() {
        return likes;
    }

    public void setLikes(String likes) {
        this.likes = likes;
    }

    public String getPlaytimes() {
        return playtimes;
    }

    public void setPlaytimes(String playtimes) {
        this.playtimes = playtimes;
    }

    public String getComments() {
        return comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    public String getShares() {
        return shares;
    }

    public void setShares(String shares) {
        this.shares = shares;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getDownloadSize() {
        return downloadSize;
    }

    public void setDownloadSize(String downloadSize) {
        this.downloadSize = downloadSize;
    }

    public String getDownloadAacSize() {
        return downloadAacSize;
    }

    public void setDownloadAacSize(String downloadAacSize) {
        this.downloadAacSize = downloadAacSize;
    }

}
